FROM node:latest

# Load wait.sh
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh

WORKDIR /app

# Install dependencies
COPY ./app/package.json .
RUN npm install

# My hacky solution to docker doing docker things. Comment out if not needed
RUN npm install -g knex npm-run-all nodemon webpack webpack-cli @babel/node @babel/core

# Bundle app source
COPY ./app /app

# Migrate data and run app
CMD /wait.sh db 5432 \
  && npm run migrate \
  && npm run devstart