version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
        - ./app:/app
        - /app/node_modules
  db:
    container_name: db
    image: "postgres:latest"
    restart: always
    volumes:
      - db:/data/db:rw
    env_file:
        - ./app/.env
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
    depends_on: 
        - app

volumes:
  db: